interface Country {
  label: string
  value: string
  code: string,
  phone: string
}

export const countries: Country[] = [
  { label: 'Afghanistan', value: 'Afghanistan', code: 'AF', phone: '+93' },
  { label: 'Albania', value: 'Albania', code: 'AL', phone: '+355' },
  { label: 'Algeria', value: 'Algeria', code: 'DZ', phone: '+213' },
  { label: 'Andorra', value: 'Andorra', code: 'AD', phone: '+376' },
  { label: 'Angola', value: 'Angola', code: 'AO', phone: '+244' },
  { label: 'Argentina', value: 'Argentina', code: 'AR', phone: '+54' },
  { label: 'Armenia', value: 'Armenia', code: 'AM', phone: '+374' },
  { label: 'Australia', value: 'Australia', code: 'AU', phone: '+61' },
  { label: 'Austria', value: 'Austria', code: 'AT', phone: '+43' },
  { label: 'Azerbaijan', value: 'Azerbaijan', code: 'AZ', phone: '+994' },
  { label: 'Bahamas', value: 'Bahamas', code: 'BS', phone: '+1242' },
  { label: 'Bahrain', value: 'Bahrain', code: 'BH', phone: '+973' },
  { label: 'Bangladesh', value: 'Bangladesh', code: 'BD', phone: '+880' },
  { label: 'Belarus', value: 'Belarus', code: 'BY', phone: '+375' },
  { label: 'Belgium', value: 'Belgium', code: 'BE', phone: '+32' },
  { label: 'Belize', value: 'Belize', code: 'BZ', phone: '+501' },
  { label: 'Benin', value: 'Benin', code: 'BJ', phone: '+229' },
  { label: 'Bhutan', value: 'Bhutan', code: 'BT', phone: '+975' },
  { label: 'Bolivia', value: 'Bolivia', code: 'BO', phone: '+591' },
  { label: 'Bosnia and Herzegovina', value: 'Bosnia and Herzegovina', code: 'BA', phone: '+387' },
  { label: 'Botswana', value: 'Botswana', code: 'BW', phone: '+267' },
  { label: 'Brazil', value: 'Brazil', code: 'BR', phone: '+55' },
  { label: 'Brunei', value: 'Brunei', code: 'BN', phone: '+673' },
  { label: 'Bulgaria', value: 'Bulgaria', code: 'BG', phone: '+359' },
  { label: 'Burkina Faso', value: 'Burkina Faso', code: 'BF', phone: '+226' },
  { label: 'Burundi', value: 'Burundi', code: 'BI', phone: '+257' },
  { label: 'Cambodia', value: 'Cambodia', code: 'KH', phone: '+855' },
  { label: 'Cameroon', value: 'Cameroon', code: 'CM', phone: '+237' },
  { label: 'Canada', value: 'Canada', code: 'CA', phone: '+1' },
  { label: 'Cape Verde', value: 'Cape Verde', code: 'CV', phone: '+238' },
  { label: 'Central African Republic', value: 'Central African Republic', code: 'CF', phone: '+236' },
  { label: 'Chad', value: 'Chad', code: 'TD', phone: '+235' },
  { label: 'Chile', value: 'Chile', code: 'CL', phone: '+56' },
  { label: 'China', value: 'China', code: 'CN', phone: '+86' },
  { label: 'Colombia', value: 'Colombia', code: 'CO', phone: '+57' },
  { label: 'Comoros', value: 'Comoros', code: 'KM', phone: '+269' },
  { label: 'Costa Rica', value: 'Costa Rica', code: 'CR', phone: '+506' },
  { label: 'Croatia', value: 'Croatia', code: 'HR', phone: '+385' },
  { label: 'Cuba', value: 'Cuba', code: 'CU', phone: '+53' },
  { label: 'Cyprus', value: 'Cyprus', code: 'CY', phone: '+357' },
  { label: 'Czech Republic', value: 'Czech Republic', code: 'CZ', phone: '+420' },
  { label: 'Denmark', value: 'Denmark', code: 'DK', phone: '+45' },
  { label: 'Djibouti', value: 'Djibouti', code: 'DJ', phone: '+253' },
  { label: 'Dominican Republic', value: 'Dominican Republic', code: 'DO', phone: '+1809' },
  { label: 'Ecuador', value: 'Ecuador', code: 'EC', phone: '+593' },
  { label: 'Egypt', value: 'Egypt', code: 'EG', phone: '+20' },
  { label: 'El Salvador', value: 'El Salvador', code: 'SV', phone: '+503' },
  { label: 'Estonia', value: 'Estonia', code: 'EE', phone: '+372' },
  { label: 'Ethiopia', value: 'Ethiopia', code: 'ET', phone: '+251' },
  { label: 'Fiji', value: 'Fiji', code: 'FJ', phone: '+679' },
  { label: 'Finland', value: 'Finland', code: 'FI', phone: '+358' },
  { label: 'France', value: 'France', code: 'FR', phone: '+33' },
  { label: 'Gabon', value: 'Gabon', code: 'GA', phone: '+241' },
  { label: 'Gambia', value: 'Gambia', code: 'GM', phone: '+220' },
  { label: 'Georgia', value: 'Georgia', code: 'GE', phone: '+995' },
  { label: 'Germany', value: 'Germany', code: 'DE', phone: '+49' },
  { label: 'Ghana', value: 'Ghana', code: 'GH', phone: '+233' },
  { label: 'Greece', value: 'Greece', code: 'GR', phone: '+30' },
  { label: 'Grenada', value: 'Grenada', code: 'GD', phone: '+1473' },
  { label: 'Guatemala', value: 'Guatemala', code: 'GT', phone: '+502' },
  { label: 'Guinea', value: 'Guinea', code: 'GN', phone: '+224' },
  { label: 'Guyana', value: 'Guyana', code: 'GY', phone: '+592' },
  { label: 'Haiti', value: 'Haiti', code: 'HT', phone: '+509' },
  { label: 'Honduras', value: 'Honduras', code: 'HN', phone: '+504' },
  { label: 'Hungary', value: 'Hungary', code: 'HU', phone: '+36' },
  { label: 'Iceland', value: 'Iceland', code: 'IS', phone: '+354' },
  { label: 'India', value: 'India', code: 'IN', phone: '+91' },
  { label: 'Indonesia', value: 'Indonesia', code: 'ID', phone: '+62' },
  { label: 'Iran', value: 'Iran', code: 'IR', phone: '+98' },
  { label: 'Iraq', value: 'Iraq', code: 'IQ', phone: '+964' },
  { label: 'Ireland', value: 'Ireland', code: 'IE', phone: '+353' },
  { label: 'Israel', value: 'Israel', code: 'IL', phone: '+972' },
  { label: 'Italy', value: 'Italy', code: 'IT', phone: '+39' },
  { label: 'Jamaica', value: 'Jamaica', code: 'JM', phone: '+1876' },
  { label: 'Japan', value: 'Japan', code: 'JP', phone: '+81' },
  { label: 'Jordan', value: 'Jordan', code: 'JO', phone: '+962' },
  { label: 'Kazakhstan', value: 'Kazakhstan', code: 'KZ', phone: '+7' },
  { label: 'Kenya', value: 'Kenya', code: 'KE', phone: '+254' },
  { label: 'Kuwait', value: 'Kuwait', code: 'KW', phone: '+965' },
  { label: 'Kyrgyzstan', value: 'Kyrgyzstan', code: 'KG', phone: '+996' },
  { label: 'Laos', value: 'Laos', code: 'LA', phone: '+856' },
  { label: 'Latvia', value: 'Latvia', code: 'LV', phone: '+371' },
  { label: 'Lebanon', value: 'Lebanon', code: 'LB', phone: '+961' },
  { label: 'Lesotho', value: 'Lesotho', code: 'LS', phone: '+266' },
  { label: 'Liberia', value: 'Liberia', code: 'LR', phone: '+231' },
  { label: 'Libya', value: 'Libya', code: 'LY', phone: '+218' },
  { label: 'Liechtenstein', value: 'Liechtenstein', code: 'LI', phone: '+423' },
  { label: 'Lithuania', value: 'Lithuania', code: 'LT', phone: '+370' },
  { label: 'Luxembourg', value: 'Luxembourg', code: 'LU', phone: '+352' },
  { label: 'Madagascar', value: 'Madagascar', code: 'MG', phone: '+261' },
  { label: 'Malawi', value: 'Malawi', code: 'MW', phone: '+265' },
  { label: 'Malaysia', value: 'Malaysia', code: 'MY', phone: '+60' },
  { label: 'Maldives', value: 'Maldives', code: 'MV', phone: '+960' },
  { label: 'Mali', value: 'Mali', code: 'ML', phone: '+223' },
  { label: 'Malta', value: 'Malta', code: 'MT', phone: '+356' },
  { label: 'Mauritania', value: 'Mauritania', code: 'MR', phone: '+222' },
  { label: 'Mauritius', value: 'Mauritius', code: 'MU', phone: '+230' },
  { label: 'Mexico', value: 'Mexico', code: 'MX', phone: '+52' },
  { label: 'Moldova', value: 'Moldova', code: 'MD', phone: '+373' },
  { label: 'Monaco', value: 'Monaco', code: 'MC', phone: '+377' },
  { label: 'Mongolia', value: 'Mongolia', code: 'MN', phone: '+976' },
  { label: 'Montenegro', value: 'Montenegro', code: 'ME', phone: '+382' },
  { label: 'Morocco', value: 'Morocco', code: 'MA', phone: '+212' },
  { label: 'Mozambique', value: 'Mozambique', code: 'MZ', phone: '+258' },
  { label: 'Myanmar', value: 'Myanmar', code: 'MM', phone: '+95' },
  { label: 'Namibia', value: 'Namibia', code: 'NA', phone: '+264' },
  { label: 'Nepal', value: 'Nepal', code: 'NP', phone: '+977' },
  { label: 'Netherlands', value: 'Netherlands', code: 'NL', phone: '+31' },
  { label: 'New Zealand', value: 'New Zealand', code: 'NZ', phone: '+64' },
  { label: 'Nicaragua', value: 'Nicaragua', code: 'NI', phone: '+505' },
  { label: 'Niger', value: 'Niger', code: 'NE', phone: '+227' },
  { label: 'Nigeria', value: 'Nigeria', code: 'NG', phone: '+234' },
  { label: 'North Korea', value: 'North Korea', code: 'KP', phone: '+850' },
  { label: 'North Macedonia', value: 'North Macedonia', code: 'MK', phone: '+389' },
  { label: 'Norway', value: 'Norway', code: 'NO', phone: '+47' },
  { label: 'Oman', value: 'Oman', code: 'OM', phone: '+968' },
  { label: 'Pakistan', value: 'Pakistan', code: 'PK', phone: '+92' },
  { label: 'Panama', value: 'Panama', code: 'PA', phone: '+507' },
  { label: 'Papua New Guinea', value: 'Papua New Guinea', code: 'PG', phone: '+675' },
  { label: 'Paraguay', value: 'Paraguay', code: 'PY', phone: '+595' },
  { label: 'Peru', value: 'Peru', code: 'PE', phone: '+51' },
  { label: 'Philippines', value: 'Philippines', code: 'PH', phone: '+63' },
  { label: 'Poland', value: 'Poland', code: 'PL', phone: '+48' },
  { label: 'Portugal', value: 'Portugal', code: 'PT', phone: '+351' },
  { label: 'Qatar', value: 'Qatar', code: 'QA', phone: '+974' },
  { label: 'Romania', value: 'Romania', code: 'RO', phone: '+40' },
  { label: 'Russia', value: 'Russia', code: 'RU', phone: '+7' },
  { label: 'Rwanda', value: 'Rwanda', code: 'RW', phone: '+250' },
  { label: 'Saudi Arabia', value: 'Saudi Arabia', code: 'SA', phone: '+966' },
  { label: 'Senegal', value: 'Senegal', code: 'SN', phone: '+221' },
  { label: 'Serbia', value: 'Serbia', code: 'RS', phone: '+381' },
  { label: 'Singapore', value: 'Singapore', code: 'SG', phone: '+65' },
  { label: 'Slovakia', value: 'Slovakia', code: 'SK', phone: '+421' },
  { label: 'Slovenia', value: 'Slovenia', code: 'SI', phone: '+386' },
  { label: 'Somalia', value: 'Somalia', code: 'SO', phone: '+252' },
  { label: 'South Africa', value: 'South Africa', code: 'ZA', phone: '+27' },
  { label: 'South Korea', value: 'South Korea', code: 'KR', phone: '+82' },
  { label: 'South Sudan', value: 'South Sudan', code: 'SS', phone: '+211' },
  { label: 'Spain', value: 'Spain', code: 'ES', phone: '+34' },
  { label: 'Sri Lanka', value: 'Sri Lanka', code: 'LK', phone: '+94' },
  { label: 'Sudan', value: 'Sudan', code: 'SD', phone: '+249' },
  { label: 'Sweden', value: 'Sweden', code: 'SE', phone: '+46' },
  { label: 'Switzerland', value: 'Switzerland', code: 'CH', phone: '+41' },
  { label: 'Syria', value: 'Syria', code: 'SY', phone: '+963' },
  { label: 'Taiwan', value: 'Taiwan', code: 'TW', phone: '+886' },
  { label: 'Tajikistan', value: 'Tajikistan', code: 'TJ', phone: '+992' },
  { label: 'Tanzania', value: 'Tanzania', code: 'TZ', phone: '+255' },
  { label: 'Thailand', value: 'Thailand', code: 'TH', phone: '+66' },
  { label: 'Togo', value: 'Togo', code: 'TG', phone: '+228' },
  { label: 'Tunisia', value: 'Tunisia', code: 'TN', phone: '+216' },
  { label: 'Turkey', value: 'Turkey', code: 'TR', phone: '+90' },
  { label: 'Turkmenistan', value: 'Turkmenistan', code: 'TM', phone: '+993' },
  { label: 'Uganda', value: 'Uganda', code: 'UG', phone: '+256' },
  { label: 'Ukraine', value: 'Ukraine', code: 'UA', phone: '+380' },
  { label: 'United Arab Emirates', value: 'United Arab Emirates', code: 'AE', phone: '+971' },
  { label: 'United Kingdom', value: 'United Kingdom', code: 'GB', phone: '+44' },
  { label: 'United States', value: 'United States', code: 'US', phone: '+1' },
  { label: 'Uruguay', value: 'Uruguay', code: 'UY', phone: '+598' },
  { label: 'Uzbekistan', value: 'Uzbekistan', code: 'UZ', phone: '+998' },
  { label: 'Vatican City', value: 'Vatican City', code: 'VA', phone: '+379' },
  { label: 'Venezuela', value: 'Venezuela', code: 'VE', phone: '+58' },
  { label: 'Vietnam', value: 'Vietnam', code: 'VN', phone: '+84' },
  { label: 'Yemen', value: 'Yemen', code: 'YE', phone: '+967' },
  { label: 'Zambia', value: 'Zambia', code: 'ZM', phone: '+260' },
  { label: 'Zimbabwe', value: 'Zimbabwe', code: 'ZW', phone: '+263' }
]