interface State {
  label: string
  value: string
  code: string
  country_code: string
}

export const states: State[] = [
  // United States
  { label: 'Alabama', value: 'Alabama', code: 'AL', country_code: 'US' },
  { label: 'Alaska', value: 'Alaska', code: 'AK', country_code: 'US' },
  { label: 'Arizona', value: 'Arizona', code: 'AZ', country_code: 'US' },
  { label: 'Arkansas', value: 'Arkansas', code: 'AR', country_code: 'US' },
  { label: 'California', value: 'California', code: 'CA', country_code: 'US' },
  { label: 'Colorado', value: 'Colorado', code: 'CO', country_code: 'US' },
  { label: 'Connecticut', value: 'Connecticut', code: 'CT', country_code: 'US' },
  { label: 'Delaware', value: 'Delaware', code: 'DE', country_code: 'US' },
  { label: 'Florida', value: 'Florida', code: 'FL', country_code: 'US' },
  { label: 'Georgia', value: 'Georgia', code: 'GA', country_code: 'US' },
  { label: 'Hawaii', value: 'Hawaii', code: 'HI', country_code: 'US' },
  { label: 'Idaho', value: 'Idaho', code: 'ID', country_code: 'US' },
  { label: 'Illinois', value: 'Illinois', code: 'IL', country_code: 'US' },
  { label: 'Indiana', value: 'Indiana', code: 'IN', country_code: 'US' },
  { label: 'Iowa', value: 'Iowa', code: 'IA', country_code: 'US' },
  { label: 'Kansas', value: 'Kansas', code: 'KS', country_code: 'US' },
  { label: 'Kentucky', value: 'Kentucky', code: 'KY', country_code: 'US' },
  { label: 'Louisiana', value: 'Louisiana', code: 'LA', country_code: 'US' },
  { label: 'Maine', value: 'Maine', code: 'ME', country_code: 'US' },
  { label: 'Maryland', value: 'Maryland', code: 'MD', country_code: 'US' },
  { label: 'Massachusetts', value: 'Massachusetts', code: 'MA', country_code: 'US' },
  { label: 'Michigan', value: 'Michigan', code: 'MI', country_code: 'US' },
  { label: 'Minnesota', value: 'Minnesota', code: 'MN', country_code: 'US' },
  { label: 'Mississippi', value: 'Mississippi', code: 'MS', country_code: 'US' },
  { label: 'Missouri', value: 'Missouri', code: 'MO', country_code: 'US' },
  { label: 'Montana', value: 'Montana', code: 'MT', country_code: 'US' },
  { label: 'Nebraska', value: 'Nebraska', code: 'NE', country_code: 'US' },
  { label: 'Nevada', value: 'Nevada', code: 'NV', country_code: 'US' },
  { label: 'New Hampshire', value: 'New Hampshire', code: 'NH', country_code: 'US' },
  { label: 'New Jersey', value: 'New Jersey', code: 'NJ', country_code: 'US' },
  { label: 'New Mexico', value: 'New Mexico', code: 'NM', country_code: 'US' },
  { label: 'New York', value: 'New York', code: 'NY', country_code: 'US' },
  { label: 'North Carolina', value: 'North Carolina', code: 'NC', country_code: 'US' },
  { label: 'North Dakota', value: 'North Dakota', code: 'ND', country_code: 'US' },
  { label: 'Ohio', value: 'Ohio', code: 'OH', country_code: 'US' },
  { label: 'Oklahoma', value: 'Oklahoma', code: 'OK', country_code: 'US' },
  { label: 'Oregon', value: 'Oregon', code: 'OR', country_code: 'US' },
  { label: 'Pennsylvania', value: 'Pennsylvania', code: 'PA', country_code: 'US' },
  { label: 'Rhode Island', value: 'Rhode Island', code: 'RI', country_code: 'US' },
  { label: 'South Carolina', value: 'South Carolina', code: 'SC', country_code: 'US' },
  { label: 'South Dakota', value: 'South Dakota', code: 'SD', country_code: 'US' },
  { label: 'Tennessee', value: 'Tennessee', code: 'TN', country_code: 'US' },
  { label: 'Texas', value: 'Texas', code: 'TX', country_code: 'US' },
  { label: 'Utah', value: 'Utah', code: 'UT', country_code: 'US' },
  { label: 'Vermont', value: 'Vermont', code: 'VT', country_code: 'US' },
  { label: 'Virginia', value: 'Virginia', code: 'VA', country_code: 'US' },
  { label: 'Washington', value: 'Washington', code: 'WA', country_code: 'US' },
  { label: 'West Virginia', value: 'West Virginia', code: 'WV', country_code: 'US' },
  { label: 'Wisconsin', value: 'Wisconsin', code: 'WI', country_code: 'US' },
  { label: 'Wyoming', value: 'Wyoming', code: 'WY', country_code: 'US' },

  // Canada
  { label: 'Alberta', value: 'Alberta', code: 'AB', country_code: 'CA' },
  { label: 'British Columbia', value: 'British Columbia', code: 'BC', country_code: 'CA' },
  { label: 'Manitoba', value: 'Manitoba', code: 'MB', country_code: 'CA' },
  { label: 'New Brunswick', value: 'New Brunswick', code: 'NB', country_code: 'CA' },
  { label: 'Newfoundland and Labrador', value: 'Newfoundland and Labrador', code: 'NL', country_code: 'CA' },
  { label: 'Northwest Territories', value: 'Northwest Territories', code: 'NT', country_code: 'CA' },
  { label: 'Nova Scotia', value: 'Nova Scotia', code: 'NS', country_code: 'CA' },
  { label: 'Nunavut', value: 'Nunavut', code: 'NU', country_code: 'CA' },
  { label: 'Ontario', value: 'Ontario', code: 'ON', country_code: 'CA' },
  { label: 'Prince Edward Island', value: 'Prince Edward Island', code: 'PE', country_code: 'CA' },
  { label: 'Quebec', value: 'Quebec', code: 'QC', country_code: 'CA' },
  { label: 'Saskatchewan', value: 'Saskatchewan', code: 'SK', country_code: 'CA' },
  { label: 'Yukon', value: 'Yukon', code: 'YT', country_code: 'CA' },

  // Australia
  { label: 'Australian Capital Territory', value: 'Australian Capital Territory', code: 'ACT', country_code: 'AU' },
  { label: 'New South Wales', value: 'New South Wales', code: 'NSW', country_code: 'AU' },
  { label: 'Northern Territory', value: 'Northern Territory', code: 'NT', country_code: 'AU' },
  { label: 'Queensland', value: 'Queensland', code: 'QLD', country_code: 'AU' },
  { label: 'South Australia', value: 'South Australia', code: 'SA', country_code: 'AU' },
  { label: 'Tasmania', value: 'Tasmania', code: 'TAS', country_code: 'AU' },
  { label: 'Victoria', value: 'Victoria', code: 'VIC', country_code: 'AU' },
  { label: 'Western Australia', value: 'Western Australia', code: 'WA', country_code: 'AU' },

  // India
  { label: 'Andhra Pradesh', value: 'Andhra Pradesh', code: 'AP', country_code: 'IN' },
  { label: 'Arunachal Pradesh', value: 'Arunachal Pradesh', code: 'AR', country_code: 'IN' },
  { label: 'Assam', value: 'Assam', code: 'AS', country_code: 'IN' },
  { label: 'Bihar', value: 'Bihar', code: 'BR', country_code: 'IN' },
  { label: 'Chhattisgarh', value: 'Chhattisgarh', code: 'CT', country_code: 'IN' },
  { label: 'Goa', value: 'Goa', code: 'GA', country_code: 'IN' },
  { label: 'Gujarat', value: 'Gujarat', code: 'GJ', country_code: 'IN' },
  { label: 'Haryana', value: 'Haryana', code: 'HR', country_code: 'IN' },
  { label: 'Himachal Pradesh', value: 'Himachal Pradesh', code: 'HP', country_code: 'IN' },
  { label: 'Jharkhand', value: 'Jharkhand', code: 'JH', country_code: 'IN' },
  { label: 'Karnataka', value: 'Karnataka', code: 'KA', country_code: 'IN' },
  { label: 'Kerala', value: 'Kerala', code: 'KL', country_code: 'IN' },
  { label: 'Madhya Pradesh', value: 'Madhya Pradesh', code: 'MP', country_code: 'IN' },
  { label: 'Maharashtra', value: 'Maharashtra', code: 'MH', country_code: 'IN' },
  { label: 'Manipur', value: 'Manipur', code: 'MN', country_code: 'IN' },
  { label: 'Meghalaya', value: 'Meghalaya', code: 'ML', country_code: 'IN' },
  { label: 'Mizoram', value: 'Mizoram', code: 'MZ', country_code: 'IN' },
  { label: 'Nagaland', value: 'Nagaland', code: 'NL', country_code: 'IN' },
  { label: 'Odisha', value: 'Odisha', code: 'OR', country_code: 'IN' },
  { label: 'Punjab', value: 'Punjab', code: 'PB', country_code: 'IN' },
  { label: 'Rajasthan', value: 'Rajasthan', code: 'RJ', country_code: 'IN' },
  { label: 'Sikkim', value: 'Sikkim', code: 'SK', country_code: 'IN' },
  { label: 'Tamil Nadu', value: 'Tamil Nadu', code: 'TN', country_code: 'IN' },
  { label: 'Telangana', value: 'Telangana', code: 'TG', country_code: 'IN' },
  { label: 'Tripura', value: 'Tripura', code: 'TR', country_code: 'IN' },
  { label: 'Uttar Pradesh', value: 'Uttar Pradesh', code: 'UP', country_code: 'IN' },
  { label: 'Uttarakhand', value: 'Uttarakhand', code: 'UT', country_code: 'IN' },
  { label: 'West Bengal', value: 'West Bengal', code: 'WB', country_code: 'IN' },

  // Brazil
  { label: 'Acre', value: 'Acre', code: 'AC', country_code: 'BR' },
  { label: 'Alagoas', value: 'Alagoas', code: 'AL', country_code: 'BR' },
  { label: 'Amapá', value: 'Amapá', code: 'AP', country_code: 'BR' },
  { label: 'Amazonas', value: 'Amazonas', code: 'AM', country_code: 'BR' },
  { label: 'Bahia', value: 'Bahia', code: 'BA', country_code: 'BR' },
  { label: 'Ceará', value: 'Ceará', code: 'CE', country_code: 'BR' },
  { label: 'Distrito Federal', value: 'Distrito Federal', code: 'DF', country_code: 'BR' },
  { label: 'Espírito Santo', value: 'Espírito Santo', code: 'ES', country_code: 'BR' },
  { label: 'Goiás', value: 'Goiás', code: 'GO', country_code: 'BR' },
  { label: 'Maranhão', value: 'Maranhão', code: 'MA', country_code: 'BR' },
  { label: 'Mato Grosso', value: 'Mato Grosso', code: 'MT', country_code: 'BR' },
  { label: 'Mato Grosso do Sul', value: 'Mato Grosso do Sul', code: 'MS', country_code: 'BR' },
  { label: 'Minas Gerais', value: 'Minas Gerais', code: 'MG', country_code: 'BR' },
  { label: 'Pará', value: 'Pará', code: 'PA', country_code: 'BR' },
  { label: 'Paraíba', value: 'Paraíba', code: 'PB', country_code: 'BR' },
  { label: 'Paraná', value: 'Paraná', code: 'PR', country_code: 'BR' },
  { label: 'Pernambuco', value: 'Pernambuco', code: 'PE', country_code: 'BR' },
  { label: 'Piauí', value: 'Piauí', code: 'PI', country_code: 'BR' },
  { label: 'Rio de Janeiro', value: 'Rio de Janeiro', code: 'RJ', country_code: 'BR' },
  { label: 'Rio Grande do Norte', value: 'Rio Grande do Norte', code: 'RN', country_code: 'BR' },
  { label: 'Rio Grande do Sul', value: 'Rio Grande do Sul', code: 'RS', country_code: 'BR' },
  { label: 'Rondônia', value: 'Rondônia', code: 'RO', country_code: 'BR' },
  { label: 'Roraima', value: 'Roraima', code: 'RR', country_code: 'BR' },
  { label: 'Santa Catarina', value: 'Santa Catarina', code: 'SC', country_code: 'BR' },
  { label: 'São Paulo', value: 'São Paulo', code: 'SP', country_code: 'BR' },
  { label: 'Sergipe', value: 'Sergipe', code: 'SE', country_code: 'BR' },
  { label: 'Tocantins', value: 'Tocantins', code: 'TO', country_code: 'BR' },

  // Mexico
  { label: 'Aguascalientes', value: 'Aguascalientes', code: 'AG', country_code: 'MX' },
  { label: 'Baja California', value: 'Baja California', code: 'BC', country_code: 'MX' },
  { label: 'Baja California Sur', value: 'Baja California Sur', code: 'BS', country_code: 'MX' },
  { label: 'Campeche', value: 'Campeche', code: 'CM', country_code: 'MX' },
  { label: 'Chiapas', value: 'Chiapas', code: 'CS', country_code: 'MX' },
  { label: 'Chihuahua', value: 'Chihuahua', code: 'CH', country_code: 'MX' },
  { label: 'Coahuila', value: 'Coahuila', code: 'CO', country_code: 'MX' },
  { label: 'Colima', value: 'Colima', code: 'CL', country_code: 'MX' },
  { label: 'Durango', value: 'Durango', code: 'DG', country_code: 'MX' },
  { label: 'Guanajuato', value: 'Guanajuato', code: 'GT', country_code: 'MX' },
  { label: 'Guerrero', value: 'Guerrero', code: 'GR', country_code: 'MX' },
  { label: 'Hidalgo', value: 'Hidalgo', code: 'HG', country_code: 'MX' },
  { label: 'Jalisco', value: 'Jalisco', code: 'JA', country_code: 'MX' },
  { label: 'México', value: 'México', code: 'ME', country_code: 'MX' },
  { label: 'Michoacán', value: 'Michoacán', code: 'MI', country_code: 'MX' },
  { label: 'Morelos', value: 'Morelos', code: 'MO', country_code: 'MX' },
  { label: 'Nayarit', value: 'Nayarit', code: 'NA', country_code: 'MX' },
  { label: 'Nuevo León', value: 'Nuevo León', code: 'NL', country_code: 'MX' },
  { label: 'Oaxaca', value: 'Oaxaca', code: 'OA', country_code: 'MX' },
  { label: 'Puebla', value: 'Puebla', code: 'PU', country_code: 'MX' },
  { label: 'Querétaro', value: 'Querétaro', code: 'QE', country_code: 'MX' },
  { label: 'Quintana Roo', value: 'Quintana Roo', code: 'QR', country_code: 'MX' },
  { label: 'San Luis Potosí', value: 'San Luis Potosí', code: 'SL', country_code: 'MX' },
  { label: 'Sinaloa', value: 'Sinaloa', code: 'SI', country_code: 'MX' },
  { label: 'Sonora', value: 'Sonora', code: 'SO', country_code: 'MX' },
  { label: 'Tabasco', value: 'Tabasco', code: 'TB', country_code: 'MX' },
  { label: 'Tamaulipas', value: 'Tamaulipas', code: 'TM', country_code: 'MX' },
  { label: 'Tlaxcala', value: 'Tlaxcala', code: 'TL', country_code: 'MX' },
  { label: 'Veracruz', value: 'Veracruz', code: 'VE', country_code: 'MX' },
  { label: 'Yucatán', value: 'Yucatán', code: 'YU', country_code: 'MX' },
  { label: 'Zacatecas', value: 'Zacatecas', code: 'ZA', country_code: 'MX' },

  // China
  { label: 'Anhui', value: 'Anhui', code: 'AH', country_code: 'CN' },
  { label: 'Beijing', value: 'Beijing', code: 'BJ', country_code: 'CN' },
  { label: 'Chongqing', value: 'Chongqing', code: 'CQ', country_code: 'CN' },
  { label: 'Fujian', value: 'Fujian', code: 'FJ', country_code: 'CN' },
  { label: 'Gansu', value: 'Gansu', code: 'GS', country_code: 'CN' },
  { label: 'Guangdong', value: 'Guangdong', code: 'GD', country_code: 'CN' },
  { label: 'Guangxi', value: 'Guangxi', code: 'GX', country_code: 'CN' },
  { label: 'Guizhou', value: 'Guizhou', code: 'GZ', country_code: 'CN' },
  { label: 'Hainan', value: 'Hainan', code: 'HI', country_code: 'CN' },
  { label: 'Hebei', value: 'Hebei', code: 'HE', country_code: 'CN' },
  { label: 'Heilongjiang', value: 'Heilongjiang', code: 'HL', country_code: 'CN' },
  { label: 'Henan', value: 'Henan', code: 'HA', country_code: 'CN' },
  { label: 'Hong Kong', value: 'Hong Kong', code: 'HK', country_code: 'CN' },
  { label: 'Hubei', value: 'Hubei', code: 'HB', country_code: 'CN' },
  { label: 'Hunan', value: 'Hunan', code: 'HN', country_code: 'CN' },
  { label: 'Inner Mongolia', value: 'Inner Mongolia', code: 'NM', country_code: 'CN' },
  { label: 'Jiangsu', value: 'Jiangsu', code: 'JS', country_code: 'CN' },
  { label: 'Jiangxi', value: 'Jiangxi', code: 'JX', country_code: 'CN' },
  { label: 'Jilin', value: 'Jilin', code: 'JL', country_code: 'CN' },
  { label: 'Liaoning', value: 'Liaoning', code: 'LN', country_code: 'CN' },
  { label: 'Macau', value: 'Macau', code: 'MO', country_code: 'CN' },
  { label: 'Ningxia', value: 'Ningxia', code: 'NX', country_code: 'CN' },
  { label: 'Qinghai', value: 'Qinghai', code: 'QH', country_code: 'CN' },
  { label: 'Shaanxi', value: 'Shaanxi', code: 'SN', country_code: 'CN' },
  { label: 'Shandong', value: 'Shandong', code: 'SD', country_code: 'CN' },
  { label: 'Shanghai', value: 'Shanghai', code: 'SH', country_code: 'CN' },
  { label: 'Shanxi', value: 'Shanxi', code: 'SX', country_code: 'CN' },
  { label: 'Sichuan', value: 'Sichuan', code: 'SC', country_code: 'CN' },
  { label: 'Taiwan', value: 'Taiwan', code: 'TW', country_code: 'CN' },
  { label: 'Tianjin', value: 'Tianjin', code: 'TJ', country_code: 'CN' },
  { label: 'Tibet', value: 'Tibet', code: 'XZ', country_code: 'CN' },
  { label: 'Xinjiang', value: 'Xinjiang', code: 'XJ', country_code: 'CN' },
  { label: 'Yunnan', value: 'Yunnan', code: 'YN', country_code: 'CN' },
  { label: 'Zhejiang', value: 'Zhejiang', code: 'ZJ', country_code: 'CN' }
]

// Helper function to get states/provinces for a specific country
export function getStatesByCountry(countryCode: string): State[] {
  return states.filter(state => state.country_code === countryCode)
}